### ISSUE TITLE
Feedback on miniex4 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [MagnusJMJ/APME#5]
Your code is neatly written with clear groupings and namings. It is very readable. I also found that the calculation is very precise and well-calculated, in terms of how the balls are made and bounced with friction and resistance. This gives a very pleasing experience, with the tensions, in interacting with your piece.

I also like the way how you implement the positive loop where it is more than just increasing the "noise" of a system, but to also consider the eventual state of breaking the system. I wonder how may you think of information aesthetics in your piece?

**Comment by MagnusJMJ** [comment]
Sorry I haven't replied to this before, I wasn't expecting new issues before this monday. :smile: 
I have to admit I don't feel like I "get" information aesthetics yet, at least not to an extent where I can competently implement it in the mini-exercise. That's why I was very focused on the notion of the feedback loop, and how it can work either as an amplifying or stabilizing system, because I felt like I had a much better grasp of that, theoretically.
